--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-12-2014   
--------------------------------------------------------
DROP TABLE "C##EJEMPLO1"."CLIENTES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."CODIGOSPOSTALESPOBLACIONES" cascade constraints;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."CLIENTES" 
   (	"IDCLIENTE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ELIMINADO" NUMBER(1,0), 
	"DNI" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODIGOSPOSTALESPOBLACIONES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."CODIGOSPOSTALESPOBLACIONES" 
   (	"IDCODIGOPOSTALPOB" NUMBER, 
	"REFCODIGOPOSTAL" NUMBER, 
	"REFPOBLACION" NUMBER, 
	"REFPROVINCIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJEMPLO1.CLIENTES
SET DEFINE OFF;
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('4','Carlos','del Cerro','Escudero','Calle secreta','1540','987456321','yomolo@yaves.com','0','05693819P');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('5','Noemi','La coba','Me lo invento','En algún lugar','49729','987526417',null,'0','04324521Z');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('1','Luis','Colmero','Rabadon','C/Zarza parrilla 2º','1462','986523417','parrilla@yahoo.es','0','02541365A');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('3','Palomino','mendoza','Peregrino','Azotea Alta','29','987456321','yaack@gas.com','0','05312578B');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('2','Filipe','Segunda','Mano','al sur','30','956321478','email@email.com','0','05641238A');
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."CLIENTES_PK" ON "C##EJEMPLO1"."CLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."CLIENTES" ADD CONSTRAINT "CLIENTES_FK1" FOREIGN KEY ("REFCPPOBLACIONES")
	  REFERENCES "C##EJEMPLO1"."CODIGOSPOSTALESPOBLACIONES" ("IDCODIGOPOSTALPOB") ENABLE;
