--------------------------------------------------------
-- Archivo creado  - domingo-diciembre-14-2014   
--------------------------------------------------------
DROP TABLE "C##EJEMPLO1"."ARTICULOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."CLIENTES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."PEDIDOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."PEDIDOSARTICULOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."TIPOCAMBIO" cascade constraints;
DROP TABLE "C##EJEMPLO1"."USUARIOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."ROLES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."PROVEEDORES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."MEDIDAS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."COMPOSICIONES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."FORMASDEPAGO" cascade constraints;
--------------------------------------------------------
--  DDL for Table ARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."ARTICULOS" 
   (	"IDARTICULO" NUMBER, 
	"REFCOMPOSICION" NUMBER, 
	"REFMEDIDA" NUMBER, 
	"PRECIO" FLOAT(126), 
	"ELIMINADO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"REFERENCIA" NUMBER, 
	"STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."ARTICULOS"."ELIMINADO" IS '0: NO ELIMINADO 1: ELIMINADO ';
   COMMENT ON COLUMN "C##EJEMPLO1"."ARTICULOS"."STOCK" IS 'CANTIDAD ARTICULO';
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."CLIENTES" 
   (	"IDCLIENTE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ELIMINADO" NUMBER(1,0), 
	"DNI" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PEDIDOS" 
   (	"IDPEDIDO" NUMBER, 
	"REFCLIENTE" NUMBER, 
	"REFUSUARIO" NUMBER, 
	"FECHA" VARCHAR2(40 BYTE), 
	"REFFORMAPAGO" NUMBER, 
	"TOTAL" FLOAT(126), 
	"PAGADO" VARCHAR2(20 BYTE), 
	"N_PEDIDO" NUMBER, 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."PEDIDOS"."PAGADO" IS 'N o S';
--------------------------------------------------------
--  DDL for Table PEDIDOSARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PEDIDOSARTICULOS" 
   (	"IDPEDIDOARTICULO" NUMBER, 
	"REFPEDIDO" NUMBER, 
	"REFARTICULO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIOVENTA" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOCAMBIO
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."TIPOCAMBIO" 
   (	"IDTIPOCAMBIO" NUMBER(4,0), 
	"DESCRIPCION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."USUARIOS" 
   (	"IDUSUARIO" NUMBER(3,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"ELIMINADO" NUMBER(1,0), 
	"IDROL" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."USUARIOS"."IDUSUARIO" IS 'IDENTIFICC##EJEMPLO1OR DEL USUARIO
';
   COMMENT ON COLUMN "C##EJEMPLO1"."USUARIOS"."NOMBRE" IS 'NOMBRE DEL USUARIO';
   COMMENT ON COLUMN "C##EJEMPLO1"."USUARIOS"."PASSWORD" IS 'CONTRASEÑA DE ACCESO';
   COMMENT ON COLUMN "C##EJEMPLO1"."USUARIOS"."ELIMINADO" IS '0 -> NO ELIMINADO 1-> ELIMINADO';
   COMMENT ON COLUMN "C##EJEMPLO1"."USUARIOS"."IDROL" IS 'PERMISOS DEL USUARIO';
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."ROLES" 
   (	"IDROL" NUMBER(1,0), 
	"NOMBREROL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."ROLES"."IDROL" IS 'IDENTIFICC##EJEMPLO1OR DEL ROL';
--------------------------------------------------------
--  DDL for Table PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PROVEEDORES" 
   (	"IDPROVEEDOR" NUMBER(5,0), 
	"CIF" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"ELIMINADO" NUMBER(1,0), 
	"NIF" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDORARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" 
   (	"IDPROVART" NUMBER(5,0), 
	"REFPROVEEDOR" NUMBER(5,0), 
	"REFARTICULO" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HISTORIALCAMBIOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" 
   (	"IDHISTOCAMBIO" NUMBER(4,0), 
	"IDUSUARIO" NUMBER(3,0), 
	"FECHA" VARCHAR2(20 BYTE), 
	"IDTIPOCAMBIO" NUMBER(4,0), 
	"OBSERVACION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEDIDAS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."MEDIDAS" 
   (	"IDMEDIDA" NUMBER(*,0), 
	"MEDIDA" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMPOSICIONES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."COMPOSICIONES" 
   (	"IDCOMPOSICION" NUMBER(*,0), 
	"COMPOSICION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORMASDEPAGO
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."FORMASDEPAGO" 
   (	"IDPAGO" NUMBER(3,0), 
	"FORMAPAGO" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."FORMASDEPAGO"."IDPAGO" IS 'IDENTIFICADOR DE LA FORMA DE PAGO';
   COMMENT ON COLUMN "C##EJEMPLO1"."FORMASDEPAGO"."ACTIVO" IS '0 -> NO ACTIVO 1-> ACTIVO
';
REM INSERTING into C##EJEMPLO1.ARTICULOS
SET DEFINE OFF;
Insert into C##EJEMPLO1.ARTICULOS (IDARTICULO,REFCOMPOSICION,REFMEDIDA,PRECIO,ELIMINADO,NOMBRE,REFERENCIA,STOCK) values ('1','0','4','25,99','0','SABANA','1234','10');
REM INSERTING into C##EJEMPLO1.CLIENTES
SET DEFINE OFF;
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('4','Carlos','del Cerro','Escudero','Calle secreta','1540','987456321','yomolo@yaves.com','0','05693819P');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('5','Noemi','La coba','Me lo invento','En algún lugar','49729','987526417',null,'0','04324521Z');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('1','Luis','Colmero','Rabadon','C/Zarza parrilla 2º','1462','986523417','parrilla@yahoo.es','0','02541365A');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('3','Palomino','mendoza','Peregrino','Azotea Alta','29','987456321','yaack@gas.com','0','05312578B');
Insert into C##EJEMPLO1.CLIENTES (IDCLIENTE,NOMBRE,APELLIDO1,APELLIDO2,DIRECCION,REFCPPOBLACIONES,TELEFONO,EMAIL,ELIMINADO,DNI) values ('2','Filipe','Segunda','Mano','al sur','30','956321478','email@email.com','0','05641238A');
REM INSERTING into C##EJEMPLO1.PEDIDOS
SET DEFINE OFF;
Insert into C##EJEMPLO1.PEDIDOS (IDPEDIDO,REFCLIENTE,REFUSUARIO,FECHA,REFFORMAPAGO,TOTAL,PAGADO,N_PEDIDO,ELIMINADO) values ('1','1','1','13/12/2014','3','25,99','S','201412131','0');
Insert into C##EJEMPLO1.PEDIDOS (IDPEDIDO,REFCLIENTE,REFUSUARIO,FECHA,REFFORMAPAGO,TOTAL,PAGADO,N_PEDIDO,ELIMINADO) values ('2','1','1','13/12/2014','3','25,99','N','201412132','1');
Insert into C##EJEMPLO1.PEDIDOS (IDPEDIDO,REFCLIENTE,REFUSUARIO,FECHA,REFFORMAPAGO,TOTAL,PAGADO,N_PEDIDO,ELIMINADO) values ('3','1','1','13/12/2014','4','25,99','N','201412133','0');
REM INSERTING into C##EJEMPLO1.PEDIDOSARTICULOS
SET DEFINE OFF;
Insert into C##EJEMPLO1.PEDIDOSARTICULOS (IDPEDIDOARTICULO,REFPEDIDO,REFARTICULO,CANTIDAD,PRECIOVENTA) values ('1','3','1','1','25,99');
REM INSERTING into C##EJEMPLO1.TIPOCAMBIO
SET DEFINE OFF;
Insert into C##EJEMPLO1.TIPOCAMBIO (IDTIPOCAMBIO,DESCRIPCION) values ('1','Añadido');
Insert into C##EJEMPLO1.TIPOCAMBIO (IDTIPOCAMBIO,DESCRIPCION) values ('2','Modificado');
Insert into C##EJEMPLO1.TIPOCAMBIO (IDTIPOCAMBIO,DESCRIPCION) values ('3','Borrado');
Insert into C##EJEMPLO1.TIPOCAMBIO (IDTIPOCAMBIO,DESCRIPCION) values ('4','Restaurar');
REM INSERTING into C##EJEMPLO1.USUARIOS
SET DEFINE OFF;
Insert into C##EJEMPLO1.USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('4','Luis','$2a$10$woQp6bc2w3UgMrbSftRImuOUlzV/sX62u9y9eJi.vWpA3S.quJwne','0','2');
Insert into C##EJEMPLO1.USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('2','Carlos','$2a$10$JIXWxPhIKHs/Q/P7es/wKuhzk9T7UhP9kubPZEUfDiTNNL0BiWVJ6','1','2');
Insert into C##EJEMPLO1.USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('3','Noemi','$2a$10$e2g3pVj6bZhB3XBo4D.WxOJYEcMofMA6fkpwA2uAU43G089Coy0RG','1','3');
Insert into C##EJEMPLO1.USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('1','ROOT','$2a$10$o15Ks1bfPYTpWaCvXPqgTOnoxi9wGP9EafD4IyfFB6vGl1Hh4Nq6K','0','1');
Insert into C##EJEMPLO1.USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('5','hola','$2a$10$.Bq7z7/YdlZ/YDcnGkQ9summ.vp.j/lOdDLd/sukV79YtE/YVfTpC','0','3');
Insert into C##EJEMPLO1.USUARIOS (IDUSUARIO,NOMBRE,PASSWORD,ELIMINADO,IDROL) values ('6','usuario','$2a$10$Ucmz7bCpOWT49Kdiiw/A0umgwPkb3Z.TvgWZRdLy1yVUix3QIjb96','0','3');
REM INSERTING into C##EJEMPLO1.ROLES
SET DEFINE OFF;
Insert into C##EJEMPLO1.ROLES (IDROL,NOMBREROL) values ('1','ROOT');
Insert into C##EJEMPLO1.ROLES (IDROL,NOMBREROL) values ('2','ADMINISTRATIVO');
Insert into C##EJEMPLO1.ROLES (IDROL,NOMBREROL) values ('3','OPERATIVO');
REM INSERTING into C##EJEMPLO1.PROVEEDORES
SET DEFINE OFF;
REM INSERTING into C##EJEMPLO1.PROVEEDORARTICULOS
SET DEFINE OFF;
REM INSERTING into C##EJEMPLO1.HISTORIALCAMBIOS
SET DEFINE OFF;
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('22','1','12/12/2014','4','Articulo restaurado ->MOTO');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('23','1','12/12/2014','4','Articulo restaurado ->COLCHON');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('25','1','12/12/2014','1','Articulo añadido ->RETRATO');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('26','1','12/12/2014','1','Pedido añadido  num_pedido->201412121');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('27','1','12/12/2014','1','Pedido añadido  num_pedido->201412121');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('28','1','12/12/2014','1','Pedido añadido  num_pedido->201412121');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('29','1','12/12/2014','1','Pedido añadido  num_pedido->201412121');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('30','1','12/12/2014','1','Pedido añadido  num_pedido->201412121');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('32','1','12/12/2014','1','Pedido añadido  num_pedido->201412122');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('33','1','12/12/2014','1','Pedido añadido  num_pedido->201412122');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('34','1','13/12/2014','1','Pedido añadido  num_pedido->201412134');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('35','1','13/12/2014','1','Pedido añadido  num_pedido->201412134');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('16','1','10/12/2014','1','Pedido añadido  num_pedido->201412105');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('17','1','10/12/2014','1','Pedido añadido  num_pedido->201412105');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('18','1','10/12/2014','1','Articulo añadido ->MAZAPAN');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('19','1','10/12/2014','1','Articulo añadido ->FUNDAPORTATIL');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('31','1','12/12/2014','1','Pedido añadido  num_pedido->201412121');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('4','5','01/12/2014','2','Usuario modificado');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('1','4','29/11/2014','3','Usuario borrado');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('2','5','29/11/2014','4','Usuario restaurado');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('3','4','29/11/2014','4','Usuario restaurado');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('5','4','01/12/2014','2','Usuario modificado');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('11','1','10/12/2014','1','Pedido añadido  num_pedido->201412101');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('12','1','10/12/2014','1','Pedido añadido  num_pedido->201412101');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('13','1','10/12/2014','1','Articulo añadido ->FUNDA');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('21','1','11/12/2014','3','Articulo eliminado ->COLCHON');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('24','1','12/12/2014','2','Articulo modificado ->SABANA');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('38','1','13/12/2014','1','Pedido añadido  num_pedido->201412135');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('39','1','13/12/2014','1','Pedido añadido  num_pedido->201412135');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('40','1','13/12/2014','1','Pedido añadido  num_pedido->201412136');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('6','0','02/12/2014','1','Añadido nuevo usuario');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('7','6','02/12/2014','2','Usuario modificado');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('8','1','08/12/2014','1','Articulo añadido ->FOTO');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('10','1','09/12/2014','1','Pedido añadido  num_pedido->20141291');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('20','1','10/12/2014','1','Articulo añadido ->SABANA');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('9','1','09/12/2014','1','Pedido añadido  num_pedido->20141292');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('14','1','10/12/2014','1','Pedido añadido  num_pedido->201412103');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('15','1','10/12/2014','1','Pedido añadido  num_pedido->201412103');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('36','1','13/12/2014','1','Pedido añadido  num_pedido->201412135');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('37','1','13/12/2014','1','Pedido añadido  num_pedido->201412136');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('41','1','13/12/2014','1','Articulo añadido ->COLCHON');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('42','1','13/12/2014','1','Articulo añadido ->MUELLES');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('43','1','13/12/2014','1','Articulo añadido ->SABANA');
Insert into C##EJEMPLO1.HISTORIALCAMBIOS (IDHISTOCAMBIO,IDUSUARIO,FECHA,IDTIPOCAMBIO,OBSERVACION) values ('44','1','13/12/2014','1','Pedido añadido  num_pedido->201412133');
REM INSERTING into C##EJEMPLO1.MEDIDAS
SET DEFINE OFF;
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('0','80 x 180 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('1','80 x 190 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('2','80 x 200 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('3','90 x 180 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('4','90 x 190 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('5','90 x 200 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('6','105 x 180 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('7','105 x 190 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('8','105 x 200 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('9','135 x 180 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('10','135 x 190 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('11','135 x 200 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('12','150 x 180 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('13','150 x 190 cm');
Insert into C##EJEMPLO1.MEDIDAS (IDMEDIDA,MEDIDA) values ('14','150 x 200 cm');
REM INSERTING into C##EJEMPLO1.COMPOSICIONES
SET DEFINE OFF;
Insert into C##EJEMPLO1.COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('4','Algodon');
Insert into C##EJEMPLO1.COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('5','Poliester');
Insert into C##EJEMPLO1.COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('0','Colchón Muelles');
Insert into C##EJEMPLO1.COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('1','Colchón Viscoelástica');
Insert into C##EJEMPLO1.COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('2','Colchón Latex');
Insert into C##EJEMPLO1.COMPOSICIONES (IDCOMPOSICION,COMPOSICION) values ('3','Colchón Enrollado');
--------------------------------------------------------
--  DDL for Index ARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."ARTICULOS_PK" ON "C##EJEMPLO1"."ARTICULOS" ("IDARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."CLIENTES_PK" ON "C##EJEMPLO1"."CLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PEDIDOS_PK" ON "C##EJEMPLO1"."PEDIDOS" ("IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDOSARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PEDIDOSARTICULOS_PK" ON "C##EJEMPLO1"."PEDIDOSARTICULOS" ("IDPEDIDOARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPOCAMBIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."TIPOCAMBIO_PK" ON "C##EJEMPLO1"."TIPOCAMBIO" ("IDTIPOCAMBIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."USUARIOS_PK" ON "C##EJEMPLO1"."USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."ROLES_PK" ON "C##EJEMPLO1"."ROLES" ("IDROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PROVEEDORES_PK" ON "C##EJEMPLO1"."PROVEEDORES" ("IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDORARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PROVEEDORARTICULOS_PK" ON "C##EJEMPLO1"."PROVEEDORARTICULOS" ("IDPROVART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HISTORIAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."HISTORIAL_PK" ON "C##EJEMPLO1"."HISTORIALCAMBIOS" ("IDHISTOCAMBIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010011
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."SYS_C0010011" ON "C##EJEMPLO1"."MEDIDAS" ("IDMEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010010
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."SYS_C0010010" ON "C##EJEMPLO1"."COMPOSICIONES" ("IDCOMPOSICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."ARTICULOS" ADD CONSTRAINT "ARTICULOS_PK" PRIMARY KEY ("IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."ARTICULOS" MODIFY ("IDARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_PK" PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDOSARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_PK" PRIMARY KEY ("IDPEDIDOARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PEDIDOSARTICULOS" MODIFY ("IDPEDIDOARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOCAMBIO
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."TIPOCAMBIO" ADD CONSTRAINT "TIPOCAMBIO_PK" PRIMARY KEY ("IDTIPOCAMBIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."TIPOCAMBIO" MODIFY ("IDTIPOCAMBIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."USUARIOS" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."USUARIOS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."ROLES" MODIFY ("NOMBREROL" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."ROLES" MODIFY ("IDROL" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("IDROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("IDPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" ADD CONSTRAINT "PROVEEDORES_PK" PRIMARY KEY ("IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("IDPROVART" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("REFPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("REFARTICULO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_PK" PRIMARY KEY ("IDPROVART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HISTORIALCAMBIOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" MODIFY ("IDHISTOCAMBIO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" MODIFY ("IDTIPOCAMBIO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" MODIFY ("OBSERVACION" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" ADD CONSTRAINT "HISTORIAL_PK" PRIMARY KEY ("IDHISTOCAMBIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEDIDAS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."MEDIDAS" ADD PRIMARY KEY ("IDMEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMPOSICIONES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."COMPOSICIONES" ADD PRIMARY KEY ("IDCOMPOSICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_FK1" FOREIGN KEY ("REFUSUARIO")
	  REFERENCES "C##EJEMPLO1"."USUARIOS" ("IDUSUARIO") ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_FPAGO" FOREIGN KEY ("REFFORMAPAGO")
	  REFERENCES "C##EJEMPLO1"."FORMASDEPAGO" ("IDPAGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOSARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_ARTICULO" FOREIGN KEY ("REFARTICULO")
	  REFERENCES "C##EJEMPLO1"."ARTICULOS" ("IDARTICULO") ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_PEDIDO" FOREIGN KEY ("REFPEDIDO")
	  REFERENCES "C##EJEMPLO1"."PEDIDOS" ("IDPEDIDO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK2" FOREIGN KEY ("REFPROVEEDOR")
	  REFERENCES "C##EJEMPLO1"."PROVEEDORES" ("IDPROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HISTORIALCAMBIOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."HISTORIALCAMBIOS" ADD CONSTRAINT "HISTORIALCAMBIOS_FK1" FOREIGN KEY ("IDHISTOCAMBIO")
	  REFERENCES "C##EJEMPLO1"."HISTORIALCAMBIOS" ("IDHISTOCAMBIO") ENABLE;
