--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-10-2014   
--------------------------------------------------------
DROP TABLE "C##EJEMPLO1"."PROVEEDORES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" cascade constraints;
--------------------------------------------------------
--  DDL for Table PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PROVEEDORES" 
   (	"IDPROVEEDOR" NUMBER(5,0), 
	"CIF" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"ELIMINADO" NUMBER(1,0), 
	"NIF" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDORARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" 
   (	"IDPROVART" NUMBER(5,0), 
	"REFPROVEEDOR" NUMBER(5,0), 
	"REFARTICULO" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into AD.PROVEEDORES
SET DEFINE OFF;
Insert into AD.PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF) values ('1','05710881G','Pablo','Ramon y cajal 19','1464','657845623','0',null);
Insert into AD.PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF) values ('2','70563538K','Jose','Paloma 20','1504','657845125','0',null);
Insert into AD.PROVEEDORES (IDPROVEEDOR,CIF,NOMBRE,DIRECCION,REFCPPOBLACIONES,TELEFONO,ELIMINADO,NIF) values ('3','05710114A','Maria','Mayor 1','1488','635874154','0',null);
REM INSERTING into AD.PROVEEDORARTICULOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PROVEEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PROVEEDORES_PK" ON "C##EJEMPLO1"."PROVEEDORES" ("IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDORARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PROVEEDORARTICULOS_PK" ON "C##EJEMPLO1"."PROVEEDORARTICULOS" ("IDPROVART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" ADD CONSTRAINT "PROVEEDORES_PK" PRIMARY KEY ("IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("IDPROVEEDOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_PK" PRIMARY KEY ("IDPROVART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("REFARTICULO" NOT NULL ENABLE);
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("REFPROVEEDOR" NOT NULL ENABLE);
 
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("IDPROVART" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK2" FOREIGN KEY ("REFPROVEEDOR")
	  REFERENCES "C##EJEMPLO1"."PROVEEDORES" ("IDPROVEEDOR") ENABLE;
