--------------------------------------------------------
-- Archivo creado  - sábado-diciembre-06-2014   
--------------------------------------------------------
DROP TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."PROVEEDORES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."ARTICULOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."CODIGOSPOSTALESPOBLACIONES" cascade constraints;
--------------------------------------------------------
--  DDL for Table PROVEEDORARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" 
   (	"IDPROVART" NUMBER(5,0), 
	"REFPROVEEDOR" NUMBER(5,0), 
	"REFARTICULO" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PROVEEDORES" 
   (	"IDPROVEEDOR" NUMBER(5,0), 
	"CIF" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ELIMINADO" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."ARTICULOS" 
   (	"IDARTICULO" NUMBER, 
	"COMPOSICION" VARCHAR2(40 BYTE), 
	"MEDIDA" VARCHAR2(40 BYTE), 
	"PRECIO" FLOAT(126), 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."ARTICULOS"."ELIMINADO" IS '0: NO ELIMINADO 1: ELIMINADO ';
--------------------------------------------------------
--  DDL for Table CODIGOSPOSTALESPOBLACIONES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."CODIGOSPOSTALESPOBLACIONES" 
   (	"IDCODIGOPOSTALPOB" NUMBER, 
	"REFCODIGOPOSTAL" NUMBER, 
	"REFPOBLACION" NUMBER, 
	"REFPROVINCIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EJEMPLO1.PROVEEDORARTICULOS
SET DEFINE OFF;
REM INSERTING into C##EJEMPLO1.PROVEEDORES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PROVEEDORARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PROVEEDORARTICULOS_PK" ON "C##EJEMPLO1"."PROVEEDORARTICULOS" ("IDPROVART") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PROVEEDORES_PK" ON "C##EJEMPLO1"."PROVEEDORES" ("IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_PK" PRIMARY KEY ("IDPROVART")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("REFARTICULO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("REFPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" MODIFY ("IDPROVART" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" ADD CONSTRAINT "PROVEEDORES_PK" PRIMARY KEY ("IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("CIF" NOT NULL ENABLE);
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" MODIFY ("IDPROVEEDOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDORARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK1" FOREIGN KEY ("REFARTICULO")
	  REFERENCES "C##EJEMPLO1"."ARTICULOS" ("IDARTICULO") ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PROVEEDORARTICULOS" ADD CONSTRAINT "PROVEEDORARTICULOS_FK2" FOREIGN KEY ("REFPROVEEDOR")
	  REFERENCES "C##EJEMPLO1"."PROVEEDORES" ("IDPROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PROVEEDORES" ADD CONSTRAINT "PROVEEDORES_FK1" FOREIGN KEY ("REFCPPOBLACIONES")
	  REFERENCES "C##EJEMPLO1"."CODIGOSPOSTALESPOBLACIONES" ("IDCODIGOPOSTALPOB") ON DELETE CASCADE ENABLE;
