--------------------------------------------------------
-- Archivo creado  - jueves-noviembre-27-2014   
--------------------------------------------------------
DROP TABLE "C##EJEMPLO1"."PEDIDOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."ARTICULOS" cascade constraints;
DROP TABLE "C##EJEMPLO1"."CLIENTES" cascade constraints;
DROP TABLE "C##EJEMPLO1"."FORMASDEPAGO" cascade constraints;
--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."PEDIDOS" 
   (	"IDPEDIDO" NUMBER, 
	"REFCLIENTE" NUMBER, 
	"REFUSUARIO" NUMBER, 
	"FECHA" DATE, 
	"REFFORMAPAGO" NUMBER, 
	"TOTAL" FLOAT(126), 
	"PAGADO" NUMBER(*,2), 
	"N_PEDIDO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ARTICULOS
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."ARTICULOS" 
   (	"IDARTICULO" NUMBER, 
	"COMPOSICION" VARCHAR2(40 BYTE), 
	"MEDIDA" VARCHAR2(40 BYTE), 
	"PRECIO" FLOAT(126), 
	"ELIMINADO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"REFERENCIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."ARTICULOS"."ELIMINADO" IS '0: NO ELIMINADO 1: ELIMINADO ';
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."CLIENTES" 
   (	"IDCLIENTE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER(5,0), 
	"TELEFONO" NUMBER(9,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ELIMINADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORMASDEPAGO
--------------------------------------------------------

  CREATE TABLE "C##EJEMPLO1"."FORMASDEPAGO" 
   (	"IDPAGO" NUMBER(3,0), 
	"FORMAPAGO" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##EJEMPLO1"."FORMASDEPAGO"."IDPAGO" IS 'IDENTIFICADOR DE LA FORMA DE PAGO';
   COMMENT ON COLUMN "C##EJEMPLO1"."FORMASDEPAGO"."ACTIVO" IS '0 -> NO ACTIVO 1-> ACTIVO
';
REM INSERTING into C##EJEMPLO1.PEDIDOS
SET DEFINE OFF;
REM INSERTING into C##EJEMPLO1.ARTICULOS
SET DEFINE OFF;
Insert into C##EJEMPLO1.ARTICULOS (IDARTICULO,COMPOSICION,MEDIDA,PRECIO,ELIMINADO,NOMBRE,REFERENCIA) values ('2','VISCOELASTICA','90X90','89','1','COLCHON','767');
Insert into C##EJEMPLO1.ARTICULOS (IDARTICULO,COMPOSICION,MEDIDA,PRECIO,ELIMINADO,NOMBRE,REFERENCIA) values ('1','LATEX','90X90','87','1','COLCHON','52984');
--------------------------------------------------------
--  DDL for Index PEDIDOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."PEDIDOS_PK" ON "C##EJEMPLO1"."PEDIDOS" ("IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EJEMPLO1"."ARTICULOS_PK" ON "C##EJEMPLO1"."ARTICULOS" ("IDARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_PK" PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."ARTICULOS" ADD CONSTRAINT "ARTICULOS_PK" PRIMARY KEY ("IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EJEMPLO1"."ARTICULOS" MODIFY ("IDARTICULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_CLIENTE" FOREIGN KEY ("REFCLIENTE")
	  REFERENCES "C##EJEMPLO1"."CLIENTES" ("IDCLIENTE") ENABLE;
  ALTER TABLE "C##EJEMPLO1"."PEDIDOS" ADD CONSTRAINT "PEDIDOS_FPAGO" FOREIGN KEY ("REFFORMAPAGO")
	  REFERENCES "C##EJEMPLO1"."FORMASDEPAGO" ("IDPAGO") ENABLE;
